Continue even if apt-get update fails

diff --git a/community-ssu-enabler b/community-ssu-enabler
--- a/community-ssu-enabler
+++ b/community-ssu-enabler
@@ -108,12 +108,20 @@ fi
 
 echo -e "\nInstalling community package $communitymp dumb meta package..."
 dpkg -i --force-all $debfile
+meta_installed="$?"
 
 echo -e "\nUpdating repository lists..."
 apt-get update
+apt_finished="$?"
 
-if [ "$?" = "0" ]
+if [ "$meta_installed" = "0" ]
 	then
+		if [ "$apt_finished" != "0" ]
+			then
+				echo "apt-get update failed, but this is not fatal."
+				echo "Press ENTER to continue..."
+				read keypress
+		fi
 		echo "backing up transistions.ini"
 		mv /usr/share/hildon-desktop/transitions.ini /usr/share/hildon-desktop/transitions.ini.precssu
 		echo "Community SSU successfully enabled. Launching Application Manager..."
